### ISSUE TITLE
Module not working with last version of ElasticSearch

### ISSUE THREAD

**Issue by hugosxm** [descrepes/mod-elastic-logs#6]
Hi,

i have a working ES cluster but the modules give me this error : 

"

[1495665874] INFO: [broker-master] Starting external process for instance elastic-logs
[1495665874] INFO: [broker-master] elastic-logs is now started ; pid=9353
[1495665874] INFO: [broker-master] Connection problem to the poller poller-geco: Connection error to http://geco.ddns.net:7771/ : Could not resolve host: geco.ddns.net
[1495665874] INFO: [broker-master] [elastic-logs[9353]]: Now running..
[1495665874] INFO: [broker-master] [elastic-logs] trying to connect to ES Cluster: 172.20.50.202:9200
[1495665874] INFO: [broker-master] [elastic-logs] connected to the ES Cluster: 172.20.50.202:9200
[1495665874] INFO: [broker-master] [elastic-logs] rotating logs ...
[1495665874] ERROR: [broker-master] [elastic-logs] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/dist-packages/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/var/lib/shinken/modules/elastic-logs/module.py", line 459, in main
    self.rotate_logs()
  File "/var/lib/shinken/modules/elastic-logs/module.py", line 361, in rotate_logs
    logger.error("[elastic-logs] Exception while rotating indices %s: %s", working_list, str(exp))
UnboundLocalError: local variable 'working_list' referenced before assignment

[1495665875] ERROR: [broker-master] The external module elastic-logs goes down unexpectedly!
[1495665875] INFO: [broker-master] Setting the module elastic-logs to restart
[1495665875] INFO: [broker-master] Trying to init module: elastic-logs

"

Elasticssearch-curator is installled, last version too, to match ES. 

Need some help here, thanks

**Comment by descrepes** [comment]
Hi,

This probably due to Curator.
As i'm not using Shinken anymore, i don't have time to maintain this module.
You can fork it and debug the code to make it work with ES 5+.

Regards
